name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (without v)"
        required: true
        type: string
      beta:
        description: "Beta release"
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix gradlew permissions
        run: chmod +x gradlew

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Build Tools
        run: sdkmanager "build-tools;35.0.0"

      - name: Build Release APK
        if: github.event.inputs.beta != 'true'
        run: ./gradlew assembleStandardRelease

      - name: Build Beta APK
        if: github.event.inputs.beta == 'true'
        run: ./gradlew assembleStandardBeta

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/standard/${{ github.event.inputs.beta == 'true' && 'beta' || 'release' }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"

      - name: Rename APK
        run: |
          mkdir output
          find app/build/outputs/apk -name "*signed.apk" -exec cp {} output/yokai-v${{ github.event.inputs.version }}.apk \;

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: yokai-v${{ github.event.inputs.version }}
          path: output/yokai-v${{ github.event.inputs.version }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Yokai v${{ github.event.inputs.version }}
          files: output/yokai-v${{ github.event.inputs.version }}.apk
          draft: false
          prerelease: ${{ github.event.inputs.beta }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
